# Generated by Django 2.2.3 on 2019-11-06 06:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191106_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 6, 17, 2, 334686, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
